name: Update Dependencies

on:
  push:
    branches:
      - main

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          python -m pip install numpy==1.19.3
          python -m pip install -r requirements.txt
